// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsSmskdBa4M6p3azDqUyeEJXIgwQxwjyI',
    appId: '1:468174057114:ios:cbf7e70ca714fa5ec9b923',
    messagingSenderId: '468174057114',
    projectId: 'workout-tracker-cccf6',
    storageBucket: 'workout-tracker-cccf6.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsSmskdBa4M6p3azDqUyeEJXIgwQxwjyI',
    appId: '1:468174057114:ios:cbf7e70ca714fa5ec9b923',
    messagingSenderId: '468174057114',
    projectId: 'workout-tracker-cccf6',
    storageBucket: 'workout-tracker-cccf6.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBppWVXHSHiBw1oohh3rwbz5HABmX6POYc',
    appId: '1:468174057114:web:009ef0eab20ee3c1c9b923',
    messagingSenderId: '468174057114',
    projectId: 'workout-tracker-cccf6',
    authDomain: 'workout-tracker-cccf6.firebaseapp.com',
    storageBucket: 'workout-tracker-cccf6.firebasestorage.app',
    measurementId: 'G-8VK71PFG4V',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBppWVXHSHiBw1oohh3rwbz5HABmX6POYc',
    appId: '1:468174057114:web:009ef0eab20ee3c1c9b923',
    messagingSenderId: '468174057114',
    projectId: 'workout-tracker-cccf6',
    authDomain: 'workout-tracker-cccf6.firebaseapp.com',
    storageBucket: 'workout-tracker-cccf6.firebasestorage.app',
    measurementId: 'G-8VK71PFG4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWetFFpYAMhGsfaCNCnc4pthGP_X9swAg',
    appId: '1:468174057114:android:4bc983025f7071d1c9b923',
    messagingSenderId: '468174057114',
    projectId: 'workout-tracker-cccf6',
    storageBucket: 'workout-tracker-cccf6.firebasestorage.app',
  );

}